version: 2

references:
  container_config: &container_config
    docker:
      - image: arti.tw.ee/circle_openjdk8:latest
        user: circleci
    resource_class: medium
    environment:
      TERM: vt100
      GRADLE_OPTS: '-Dorg.gradle.console=plain'
  working_directory: &working_directory
    working_directory: ~/url-locale

jobs:
  build:
    <<: *working_directory
    <<: *container_config
    steps:
      - checkout
      - restore_cache:
          key: url-locale-gradle-{{ checksum "build.gradle" }}-{{ checksum "gradle.properties" }}
      - run:
          name: Assemble jar
          command: ./gradlew assemble --refresh-dependencies --console=plain --no-daemon
      - run:
          name: Run tests
          command: ./gradlew check --console=plain --no-daemon --stacktrace
      - save_cache:
          paths:
            - ~/.gradle/
          key: url-locale-gradle-{{ checksum "build.gradle" }}-{{ checksum "gradle.properties" }}
      - store_test_results:
          path: ./url-locale-core/build/test-results/
      - store_test_results:
          path: ./url-locale-starter/build/test-results/
      - persist_to_workspace:
          root: .
          paths:
            - '*'
  artifacts-publish:
    <<: *working_directory
    <<: *container_config
    resource_class: small
    steps:
      - attach_workspace:
          at: ~/url-locale
      - restore_cache:
          key: url-locale-gradle-{{ checksum "build.gradle" }}-{{ checksum "gradle.properties" }}
      - run:
          name: Publish artifacts
          command: |
            if ./.circleci/version-changed.sh url-locale-core ; then
              ./gradlew publish --no-daemon --console=plain
            fi
      - run:
          name: Publish artifacts
          command: |
            if ./.circleci/version-changed.sh url-locale-starter ; then
              ./gradlew publish --no-daemon --console=plain
            fi

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build
      - artifacts-publish:
          context: artifactory-deploy
          requires:
            - build
          filters:
            branches:
              only:
                - master
